### ISSUE TITLE
Warning: An error occurred while requesting the API

### ISSUE THREAD

**Issue by abzh423** [naskio/docker-strapi#2]
That's what I get in the console of the browser, when trying to connect the first time to strapi:
`Refused to connect to 'http://localhost:1337/admin/init' because it violates the following Content Security Policy directive: "connect-src 'self' https:".`
`Refused to connect to 'http://localhost:1337/admin/project-type' because it violates the following Content Security Policy directive: "connect-src 'self' https:".`
```
Error: Network Error
    at M.exports (main.6dad6108.js:8014:7821)
    at E.onerror (main.6dad6108.js:8014:2814)
```

Also, I get the message from strapi:
`Warning: An error occurred while requesting the API`

**Comment by naskio** [comment]
Hello @abzh423 
Thanks for reporting
This error is related to Strapi itself and not the docker image
You many find the following link helpful [fix](https://forum.strapi.io/t/getting-warning-an-error-occurred-while-requesting-the-api-when-opening-strapi/13873)

**Comment by abzh423** [comment]
@naskio How do I run those commands if they give me error when executed?

**Comment by abzh423** [comment]
@naskio Thanks, now everything is working.
