### ISSUE TITLE
Cant host on subdomain or different port

### ISSUE THREAD

**Issue by YeonV** [naskio/docker-strapi#4]
PUBLIC_URL is set to `https://s.example.com' via docker-compose and port is set to 1338:
![image](https://user-images.githubusercontent.com/28861537/190044160-89f430ed-73d7-4775-9147-2349f4fb215f.png)
Although the is port is runing correctly on 1338, it tries to resolve some parts via 1337:
![image](https://user-images.githubusercontent.com/28861537/190040974-b6143fcf-ed66-40ff-8926-0fc849f43447.png)
when i set host to 'https://s.example.com' inside server.js, i get
![image](https://user-images.githubusercontent.com/28861537/190041163-4d4844e2-7376-4a8c-8419-70860eca9e27.png)

**Comment by santiblanko** [comment]
@YeonV the idea is to run strapi behind a reverse proxy.

**Comment by YeonV** [comment]
> santiblanko

thanks bro! I got some help in the discord channel and now everything is working.
I needed to create a docker-image with my own settings. now the specified port is used accordingly.

I used strapi dockerize to create the image

**Comment by nguyenk** [comment]
Hello @YeonV !

I thnk I'm having exactly the same issue (strapi behing traefik reverse proxy) should you please share some details on how you fixed this ?

This would save my life (or a leat spare me a lot of troubles :) )

Thank you !
